#!/bin/bash
for arg in "$@"
do
case $arg in
	-f|--file)
		cat $2 | curl -s -F c=@- https://ptpb.pw/?u=1;;
	-s|--screenshot)
		maim -u -s | curl -s -F c=@- https://ptpb.pw/?u=1 | awk '{print $0".png"}';;
	-u|--url)
		curl -s -F c=@- https://ptpb.pw/u?u=1 <<< $2;;
	-h|--help)
		echo "Written by Jake Marin (jmarin217)"
		echo "Options include:"
		echo "	-f or --file : upload a file."
		echo "	-s or --screenshot : upload a screenshot."
		echo "	-u or --url : shorten a url."
		echo "Syntax:"
		echo "	pussy -f <filename>"
		echo "	pussy -s"
		echo "	pussy -u <url>"
esac
done
if [[ $1 = "" ]]; then
	echo "Written by Jake Marin (jmarin217)"
	echo "Options include:"
	echo "	-f or --file : upload a file."
	echo "	-s or --screenshot : upload a screenshot."
	echo "	-u or --url : shorten a url."
	echo "Syntax:"
	echo "	pussy -f <filename>"
	echo "	pussy -s"
	echo "	pussy -u <url>"
fi
